# Generated by Django 3.1.1 on 2020-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrreader', '0009_auto_20201026_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='purse',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
