# Generated by Django 3.1.1 on 2020-10-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrreader', '0002_auto_20201017_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='qrreader.course'),
        ),
    ]
