# Generated by Django 3.1.1 on 2020-10-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrreader', '0004_auto_20201017_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='qr_img',
        ),
    ]
