# Generated by Django 3.1.1 on 2020-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrreader', '0006_auto_20201023_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='clients_came',
            field=models.ManyToManyField(blank=True, to='qrreader.Client'),
        ),
    ]
