# Generated by Django 3.1.1 on 2020-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrreader', '0010_client_purse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='value',
        ),
        migrations.AddField(
            model_name='course',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
